spring:
    application:
        name: accounts-service

    security:
        jwt:
            secret: 129uK0rEfjBgRBOnD4ax32OagxZh7Ug/cgsBXVr6doY=
            expiration: 3600000

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://database-accoutns:5433/postgres
        username: postgres
        password: postgres

    jpa:
        database: postgresql
        hibernate:
            ddl-auto: create-drop

        show-sql: true
        defer-datasource-initialization: true

    data:
        jdbc:
            dialect: postgresql

server:
    port: 8002

